<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
p { clear: both; }
.submit { margin-left: 12em; }

</style>

<p>Leave approval pending:</p>
<p>

	<table border="1">
		<tr>
			<th>Employee</th>
			<th>From</th>
			<th>To</th>
			<th>Reason</th>	
		</tr>
		<?php
	 			foreach($this->levData as $eachLev)
				{ 
					print "<tr>";
					print "<td>" .$eachLev['empName'] . "</td><td>" . $eachLev['fromDate']. "</td><td>" .$eachLev['toDate']. "</td><td>" .$eachLev['leavDesc'] . "</td>";
					print "</tr>";
				} 
			?>
		
	</table>

</p>

<p>
	<form method="post" action="approveleav">
		<p>
     <label >Employee:</label>
     <SELECT  name="selEmp">
     	<?php 
     	foreach($this->levData as $eachemp)
     	{
     		echo "<option value=\"".$eachemp['leavID']."\">".$eachemp['empName']."</option>\n  ";
     		
     	}
     	
     	?>
     </SELECT>
   	</p>
	
	 <input type="submit" value="Approve" name="Approve"/>
	 <input type="submit" value="Disapprove" name="Disapprove"/>
	</form>

</p>
