<script src="../scripts/jquery-1.8.3.js"></script>
<script src="../scripts/jquery-ui.js"></script>
<link rel="stylesheet" href="../styles/jquery-ui.css" />

<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
p { clear: both; }
.submit { margin-left: 12em; }

</style>

<script>
$(function() 
		 {
			$( "#txtEndDate" ).datepicker({
				changeMonth: true,
				changeYear: true,
				minDate: "+0D",
				showAnim: "slide",
				dateFormat: "yy-mm-dd" 
			
			});
			});

</script>


<form id="frmAsnTsk" method="post" action="assigntask">
<p>
     <label >Task:</label>
	<textarea rows="5" cols="20" maxlength="200" name="txtDesc"></textarea>		
</p>
<p>
	<label >Deadline:</label>
	<input type="text" name="txtEndDate" size="23" id="txtEndDate" readonly>
</p>
<input type="hidden" name="prid" value="<?php echo $_GET['prjid']?>">

<p>
     <input type="submit" value="Assign" name="Assign"/>
</p>

</form>

