
<script src="/scripts/jquery-1.8.3.js"></script>
<script src="/scripts/jquery-ui.js"></script>
<link rel="stylesheet" href="/styles/jquery-ui.css" />

<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
label.error { float: none; color: red; padding-left: .5em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 12em; }

</style>

<script>
$(function() 
		 {
			$( "#txtDate" ).datepicker({
				changeMonth: true,
				changeYear: true,
				minDate: "+0D",
				showAnim: "slide",
				dateFormat: "yy-mm-dd", 
				beforeShowDay: $.datepicker.noWeekends 
			});
			});
			

</script>

 <form id="frmCrEvnt" method="post" action="createevent">


	 <p>
     <label for="usrName">Event Name:</label>
     <input name="txtEvName" size="25" />
   	</p>
   
	<p>
     <label for="date">Date:</label>
     <input name="txtDate" size="25"  id="txtDate" readonly/>
   	</p>

   <p>
     <input type="submit" value="Submit" name="Create"/>
   </p>

 </form>


