<?php
	# SETTINGS
	$max_width = 100;
	$max_height = 100;
	
	function getPictureType($ext) {
		if ( preg_match('/jpg|jpeg/i', $ext) ) {
			return 'jpg';
		} else if ( preg_match('/png/i', $ext) ) {
			return 'png';
		} else if ( preg_match('/gif/i', $ext) ) {
			return 'gif';
		} else {
			return '';
		}
	}
	
	function getPictures() {
		//global $max_width, $max_height;
		If (Zend_Session::sessionExists())
			$sess = new Zend_Session_Namespace ( 'admin_emp' );

		$max_width = 100;
		$max_height = 100;
		if ( $handle = opendir("pictures/" .$sess->username) ) { 
			$lightbox = rand(); 
			echo '<ul id="pictures">';
			while ( ($file = readdir($handle)) !== false ) { 
				if ( !is_dir($file) ) {
					$split = explode('.', $file); 
					$ext = $split[count($split) - 1];
					if ( ($type = getPictureType($ext)) == '' ) {
						continue;
					}
					if ( ! is_dir('thumbs/'.$sess->username ) ) {//print_r($file) ;exit;
						mkdir('thumbs/'.$sess->username);
					}
					if ( ! file_exists('thumbs/'.$sess->username.'/'.$file) ) {
						if ( $type == 'jpg' ) {
							$src = imagecreatefromjpeg("pictures/".$sess->username."/" . $file);
						} else if ( $type == 'png' ) {
							$src = imagecreatefrompng("pictures/".$sess->username."/" . $file);//echo $src;exit;
						} else if ( $type == 'gif' ) {
							$src = imagecreatefromgif("pictures/".$sess->username."/" . $file);
						}
						if ( ($oldW = imagesx($src)) < ($oldH = imagesy($src)) ) {
							$newW = $oldW * ($max_width / $oldH);
							$newH = $max_height;
						} else { 
							$newW = $max_width;
							$newH = $oldH * ($max_height / $oldW);
						}//echo $newW . " " .$newH;exit;
						$new = imagecreatetruecolor($newW, $newH);
						imagecopyresampled($new, $src, 0, 0, 0, 0, $newW, $newH, $oldW, $oldH);
						if ( $type == 'jpg' ) {
							imagejpeg($new, 'thumbs/'.$sess->username.'/'.$file);
						} else if ( $type == 'png' ) {
							imagepng($new, 'thumbs/'.$sess->username.'/'.$file);
						} else if ( $type == 'gif' ) {
							imagegif($new, 'thumbs/'.$sess->username.'/'.$file);
						}
						imagedestroy($new);
						imagedestroy($src);
					}
					echo '<li><a href="/pictures/'.$sess->username.'/'.$file.'" rel="lightbox['.$lightbox.']">';
					echo '<img src="/thumbs/'.$sess->username.'/'.$file.'" alt="" />';
					echo '</a></li>';
				}
			}
			echo '</ul>';
		}
		
	}
?>

<meta http-equiv="Content-Type" content="text/html; charset=UFT-8" />
<link rel="stylesheet" href="/styles/lightbox.css" type="text/css" media="screen" />
<style type="text/css">
#pictures li {
	float:left;
	height:<?php echo ($max_height + 10); ?>px;
	list-style:none outside;
	width:<?php echo ($max_width + 10); ?>px;
	text-align:center;
}
img {
	border:0;
	outline:none;
}
</style>

<script type="text/javascript" src="/scripts/prototype.js"></script>
<script type="text/javascript" src="/scripts/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="/scripts/lightbox.js"></script>




<?php getPictures(); ?>




