<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
p { clear: both; }
.submit { margin-left: 12em; }
</style>

<form id="frmupload" method="post" action="managepic" enctype="multipart/form-data">

	<p>
	<label for="file">Choose File:</label>
	<input type="file" name="file" id="file">
	</p>
	<p>
	<input type="submit" name="Upload" value="Upload">
	</p>


</form>
