<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
p { clear: both; }
.submit { margin-left: 12em; }

</style>

<script src="../scripts/jquery-1.8.3.js"></script>
<script src="../scripts/jquery-ui.js"></script>
<link rel="stylesheet" href="../styles/jquery-ui.css" />

<script>
$(function() {
			$( "#txtFrom" ).datepicker({
				changeMonth: true,
				changeYear: true,
				numberOfMonths: 3,
				minDate: "+0D",
				showAnim: "slide",
				dateFormat: "yy-mm-dd",
				onClose: function( selectedDate ) {
					 $( "#txtTo" ).datepicker( "option", "minDate", selectedDate );
				}
			
			});
			$( "#txtTo" ).datepicker({
				changeMonth: true,
				changeYear: true,
				numberOfMonths: 3,
				showAnim: "slide",
				dateFormat: "yy-mm-dd",
				onClose: function( selectedDate ) {
					 $( "#txtFrom" ).datepicker( "option", "maxDate", selectedDate );
				}
			
			});
			});

</script>

<form method="post" action="applyleave">
<p>
    <label >Choose period:</label>
	<input type="text" name="txtFrom" id="txtFrom">	to 
	<input type="text" name="txtTo" id="txtTo">	
</p>

<p>
	<label >Description:</label>
	<textarea name="txtDesc" rows="7"></textarea>
</p>
<p>
	<input type="submit" name="Apply" value="Apply">
</p>
</form>
