<html>
<head>
<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 10em; float: left; }
p { clear: both; }
.submit { margin-left: 12em; }

</style>
  
</head>
<body>
  

 <form id="frm" method="post" action="login">


	 <p>
     <label for="usrName">User Name:</label>
     <input name="txtUsrname" size="25" />
   	</p>
   
	<p>
     <label for="pass">Password:</label>
     <input type="password" name="txtPassword" size="25"/>
   	</p>

   <p>
     <input type="submit" value="Submit" name="Login"/>
   </p>

 </form>
</body>
</html>
<?php
